---

collections:
  - name: ansible.posix
    version: 1.3.0
    # type: git
    # source: https://github.com/ansible-collections/ansible.posix.git

  - name: community.crypto
    version: 1.8.0
    # type: git
    # source: https://github.com/ansible-collections/community.crypto.git

  - name: community.general
    version: 3.5.0
    # type: git
    # source: https://github.com/ansible-collections/community.general.git
