---

- set_fact:
    server_key_path: "{{ pki_server_keys_dir }}/{{ item.filename_base }}.key"
    server_cert_path: "{{ pki_server_certs_dir }}/{{ item.filename_base }}.crt"

- name: Create private key for server {{ item.cn }}
  community.crypto.openssl_privatekey:
    select_crypto_backend: cryptography
    path: "{{ server_key_path }}"
    type: "RSA"
    size: 4096

- name: Create certificate signing request (CSR) for server certificate
  community.crypto.openssl_csr_pipe:
    select_crypto_backend: cryptography
    privatekey_path: "{{ server_key_path }}"
    common_name: "{{ item.cn }}"
    use_common_name_for_san: false
    subject_alt_name: "{{ item.san }}"
    basic_constraints_critical: true
    key_usage:
      - digitalSignature
      - keyAgreement
    key_usage_critical: true
    extended_key_usage:
      - serverAuth
    extended_key_usage_critical: true
  register: server_csr
  changed_when: false

- name: Sign certificate with our CA
  community.crypto.x509_certificate:
    select_crypto_backend: cryptography
    provider: ownca
    path: "{{ server_cert_path }}"
    csr_content: "{{ server_csr.csr }}"
    ownca_path: "{{ ca_cert_path }}"
    ownca_privatekey_path: "{{ ca_key_path }}"
    ownca_privatekey_passphrase: "{{ pki_ca_key_passphrase }}"
    ownca_not_after: "+730d"  # valid for two years
    ownca_not_before: "-1d"  # valid since yesterday
